### PR TITLE
(Ready for review) Improve start command on windows

### PR DESCRIPTION
**Pull request by wonderwhy-er**
# PR Description

## Summary
This pull request introduces two changes to improve the project setup and usability:

1. **Update `.gitignore`**:
   - Added `/.history` to `.gitignore` to prevent tracking IDE/editor-specific history files.

2. **Improve `start` Command for Cross-Platform Compatibility**:
   - Added platform-specific start commands:
     - `start:windows`: Simplified command for running the project on Windows without requiring bindings.
     - `start:unix`: Existing start command for Unix-based systems with bindings.
   - Updated the `start` script to detect the operating system dynamically and execute the appropriate command.

---

## Motivation

On my channel I often get people complain of it not working on windows due to that
One example here: https://www.youtube.com/watch?v=-VkGI-cUaWw&lc=Ugy8rg_sGmOLSp7JoaN4AaABAg

---

## Problem Addressed
The previous `start` command failed on Windows systems due to incompatible syntax for handling bindings. This issue required either manual adjustments or using a Linux subsystem, creating friction for Windows users.

---

## Solution
The updated `start` script dynamically detects the operating system:
- **On Windows**: Skips bindings, as they are usually not required for local development.
- **On Unix-based systems**: Executes the original command with bindings.

---

## Changes
1. **`.gitignore`**:
   - Added `/.history` to avoid unnecessary clutter from history files.
   
2. **`package.json`**:
   - Added `start:windows` and `start:unix` commands.
   - Refactored the `start` command to dynamically detect the operating system and run the appropriate script.

---

## Testing
- Verified the `start` command runs successfully on both Windows and Unix-based systems.
- Confirmed that bindings are correctly skipped on Windows.

---

## Impact
- Simplifies the development experience for Windows users.
- Maintains compatibility for Unix-based environments.

### CODE REVIEW

**Comment by kustomzone** [comment]
` "typecheck": "tsc"` is appended to the end of the start command, also listed later in the scripts.
Duplicate warning on startup.

**Comment by wonderwhy-er** [comment]
> ` "typecheck": "tsc"` is appended to the end of the start command, also listed later in the scripts. Duplicate warning on startup.

Woah ups, something went off with cherry pick... Fixed now.

**Comment by dustinwloring1988** [comment]
This has been added in a merged commit, thanks [wonderwhy-er](https://github.com/wonderwhy-er)

**Comment by wonderwhy-er** [comment]
@dustinwloring1988 hm, something is off about how you do it, this way you are seen as author of all the work in git history.
That's undesirable, you will end up demotivating people.

Why not just merge here? Conflicts? 

I think there should be way to merge without loosing authorship of code.

**Pull request merged**
