### PR TITLE
Git import from url

### PR DESCRIPTION
**Pull request by thecodacus**
# Import git repo from url

# Preview

https://github.com/user-attachments/assets/c91d4da5-5adc-4bda-9925-701c3d60caa3

### CODE REVIEW

**Comment by coleam00** [comment]
Nice work @thecodacus!! I love it!

When you import a Git repo into Bolt.new this way it will typically run the necessary NPM commands to show the preview. Do you have an idea how you would extend this to accomplish that?

**Comment by dustinwloring1988** [comment]
Works on Windows and Linux

**Comment by thecodacus** [comment]
> Nice work @thecodacus!! I love it!
> 
> When you import a Git repo into Bolt.new this way it will typically run the necessary NPM commands to show the preview. Do you have an idea how you would extend this to accomplish that?

hi @coleam00 , yes @wonderwhy-er added one PR that finds if the repo is an npm repo and has a dev command. and the adds these commands when importing. once thats imported I can integrate that with this. no point on replicating the same work 😄

**Comment by wonderwhy-er** [comment]
> > Nice work @thecodacus!! I love it!
> > When you import a Git repo into Bolt.new this way it will typically run the necessary NPM commands to show the preview. Do you have an idea how you would extend this to accomplish that?
> 
> hi @coleam00 , yes @wonderwhy-er added one PR that finds if the repo is an npm repo and has a dev command. and the adds these commands when importing. once thats imported I can integrate that with this. no point on replicating the same work 😄

I just merged that PR, that functionality is now used for both git and folder import.

@coleam00 FYI too.

**Pull request merged**
