### PR TITLE
Huggingface Models Integrated

### PR DESCRIPTION
**Pull request by ahsan3219**
I have integrated the following **Hugging Face models** into our project for enhanced code and chat instruction capabilities:

1. Qwen/Qwen2.5-Coder-32B-Instruct labeled as Qwen2.5-Coder-32B-Instruct (HuggingFace) provided by Hugging Face.
2. 01-ai/Yi-1.5-34B-Chat labeled as Yi-1.5-34B-Chat (HuggingFace) provided by Hugging Face.
3. codellama/CodeLlama-34b-Instruct-hf labeled as CodeLlama-34b-Instruct (HuggingFace) provided by Hugging Face.
4. NousResearch/Hermes-3-Llama-3.1-8B for expanded capabilities.

This integration aims to support diverse coding and chat-oriented tasks within our project ecosystem. 
**Let me know if you have any questions or need further details.**

image
image
image

### CODE REVIEW

**Comment by wonderwhy-er** [comment]
Thanks for contribution.
Remove yarn.lock as this project does not use yarn.

I will test it bit later.

**Comment by ahsan3219** [comment]
Thanks

**Comment by wonderwhy-er** [comment]
> Thanks

Will you remove yarn.lock? I can then test and merge if it works well.

I also looked at integrating dynamic list of models
Filtered by code and its sorted by downloads to show popular models
https://huggingface.co/api/models?filter=code&sort=downloads

But list of hugging face models is huge.
Make me think that we should only show top models and allow searching dynamically...


It just that with hardcoded models next week new one will come out and we will need to have new PR for it...

**Comment by ahsan3219** [comment]
> @ahsan3219, Kindly remove the yarn.lock so @wonderwhy-er can review and implement this. @wonderwhy-er, Agreed, showing top models and dynamic search would be more effective, especially with the release of new models. I'm excited about the integration of Hugging Face models, there are so many excellent options available, in my opinion.
> 
> > But list of hugging face models is huge. Makes me think that we should only show top models and allow searching dynamically...

I have deleted yarn.lock file you can test it with npm

**Comment by wonderwhy-er** [comment]
Do you want to add any information or how to feature you in case some of youtubers will be mentioning you in ottodev update videos?

**Comment by ahsan3219** [comment]
I will add other AI services and more AI models in this project so I have a lot to do to contribute in this open source Devine alternative....

**Pull request merged**
