### PR TITLE
Improve UI/UX

### PR DESCRIPTION
**Pull request by Xeven777**
Screenshot 2024-11-23 194416

- Better UI
- Inter font to make it look sleeker
- added a toggle button to hide the model selection while chatting
- added a sleek blueish blur
- turn the example prompts into cool looking badges

### CODE REVIEW

**Comment by thecodacus** [comment]
your PR has bun.lock file and pnpm lock file is deleted, can you revert that and use pnpm lock file as thats the package manager we are using

**Comment by wonderwhy-er** [comment]
You removed lock file, can you add it back? CI/CD fails due to that

**Comment by Xeven777** [comment]
> your PR has bun.lock file and pnpm lock file is deleted, can you revert that and use pnpm lock file as thats the package manager we are using

okay sure @thecodacus @wonderwhy-er . sorry my bad. i was using bun.

**Comment by Xeven777** [comment]
### Fixed and enhanced styling of copy button:
Screenshot 2024-11-24 230142



### Reduce font size for the model (it was unnecessarily huge earlier):
Screenshot 2024-11-24 230201



### Added a toggle button for model  @selection:
Screenshot 2024-11-24 230225
Screenshot 2024-11-24 230247

@thecodacus @wonderwhy-er

**Comment by coleam00** [comment]
@Xeven777 Could you take a look at @wonderwhy-er's questions when you get the chance? Thanks!

**Comment by Xeven777** [comment]
okays sure @coleam00 @wonderwhy-er

**Comment by Xeven777** [comment]
I have done those changes 😊😇 @thecodacus @wonderwhy-er @coleam00 @jasonm23

**Comment by dustinwloring1988** [comment]
This has been added in a merged commit, thanks [Xeven777](https://github.com/Xeven777)

**Pull request closed without merging**
