### PR TITLE
[feat]: Implement chat description editing in sidebar and header, add…

### PR DESCRIPTION
**Pull request by PuneetP16**
# 📝 Enhanced Chat Description Management 
(Its about chat title, but in the db its a value of chat description. So using term description instead for consistency)

## Overview
This PR introduces a chat description management system, improving the user experience by allowing dynamic editing of chat titles both in the header and sidebar.

### Motivation
The current chat description functionality lacks inline editing capabilitie and since the chat description is ai auto-generated, users may require to explicitly update it to their liking. 
Also there is no visual cue for active chat in the sidebar which makes it difficult when performing action to the active chat like deleting it. 
This PR aims to address these.

## Key Changes
- 🎯 Added chat description inline editing functionality in both header and sidebar
- 🔄 Implemented real-time synchronization between header and sidebar descriptions
- ✨ Added new `useEditChatDescription` custom hook for reusable description management
- 🔒 Added input validation for chat descriptions (open to update rules for accepted description text)
- ⌨️ Added keyboard navigation support for editing (Esc to cancel, Enter to save)
- 🏗️ Restructured header component for better conditional rendering

## Code Changes

1. **Chat Description Management**
   - Implemented a new hook: `useEditChatDescription` for managing chat description editing state and logic.
   - Added validation for descriptions to ensure they are between 1 and 100 characters and only contain alphanumeric characters.
   - Enhanced functionality for updating descriptions in both IndexedDB and the global application state.

2. **Header Component**
   - Wrapped `ChatDescription` rendering logic with a `chat.started` condition to prevent unnecessary UI elements when no chat description is set.
   - Improved UI consistency by ensuring that the edit pencil icon is displayed only when a description is available.

3. **Sidebar and History Items**
   - Modified the `HistoryItem` component to include an inline editing form for descriptions, ensuring real-time updates and a seamless user experience.
   - Added a `ChatActionButton` helper component for cleaner and reusable button logic with tooltips.
   - Highlighted the active chat in the sidebar with updated styling for better navigation.

4. **Persistence Updates**
   - Updated `setMessages` and  implemented `updateChatDescription` functions in `db.ts` to support description updates with timestamp validation.
   - Subscribed to description store updates in `Menu.client.tsx` to dynamically refresh the sidebar when descriptions change.

5. **Codebase Organization**
   - Refactored reusable logic into separate components and hooks (`useEditChatDescription`, `ChatActionButton`) for better code modularity.
   - Ensured consistent formatting, naming conventions, and adherence to coding standards.

## Testing Done
- ✅ Tested description editing in both header and sidebar
- ✅ Verified real-time synchronization between components
- ✅ Validated input constraints (alphanumeric, length limits)
- ✅ Tested error scenarios and edge cases
- ✅ Verified IndexedDB persistence
- ✅ Tested keyboard interactions

## Preview
https://github.com/user-attachments/assets/41bcefb2-2a55-4229-962d-a47995a244a9

## Breaking Changes
None.

## Checklist
- [x] Changes are responsive and work across different screen sizes
- [x] Manually tested across different screen sizes

### CODE REVIEW

**Comment by dustinwloring1988** [comment]
@PuneetP16 please fix the conflicts so we can look at the merge the video looks great.

**Comment by PuneetP16** [comment]
> @PuneetP16 please fix the conflicts so we can look at the merge the video looks great.

Resolved the conficts.

**Comment by dustinwloring1988** [comment]
Thanks for updating however I get the following when running on a Windows 11, with the app in docker and ollama in docker.

error

**Comment by thecodacus** [comment]
> Thanks for updating however I get the following when running on a Windows 11, with the app in docker and ollama in docker.
> 
> error

I believe this is a different bug I have added a fix for that #513

**Comment by thecodacus** [comment]
this looks good.. thanks for the contribution @PuneetP16 
I have made some minor adjustments. 
this is good to merge

**Pull request merged**
