### PR TITLE
feat(UI): added artifact bundling for custom long artifacts like uploading folder

### PR DESCRIPTION
**Pull request by thecodacus**
# Artifact bundling for custom long artifacts

Added a simple change to hide long artifact triggered by manual actions 

# Preview
Screenshot 2024-12-02 at 6 27 51 PM

### CODE REVIEW

**Comment by dustinwloring1988** [comment]
Should we not skip images?

image

**Comment by thecodacus** [comment]
okay thats part of the folder import PR that is merged not this PR. I also want to put images into the import but with the current method using chats its not possible to add anything other than text documents

**Comment by thecodacus** [comment]
and this needs to be fixed in some other PR

**Comment by thecodacus** [comment]
@dustinwloring1988 , @wonderwhy-er , I am merging this as this only has minor visual changes.

**Pull request merged**
