### PR TITLE
fix(project-reload): execution order is fix, this fixes the inconsistency on project reload

### PR DESCRIPTION
**Pull request by thecodacus**
# Fix Action Execution Order and Command Synchronization

## Overview
This PR implements a global execution queue to ensure proper synchronization of file operations and shell commands, particularly during project reloads and code streaming. It addresses issues with command execution order and eliminates UI flickering during code streaming operations.

### 1. Global Execution Queue
- Added `#globalExecutionQueue` to `WorkbenchStore` to manage sequential execution
- Implemented queue management methods to ensure operations run in correct order
- Modified action handling to respect queue ordering

### 2. Action Runner Updates
- Made start actions non-blocking while maintaining execution order
- Added delay between start actions to prevent race conditions
- Improved promise chain handling in action execution

### 3. Workbench Store Improvements
- Split action handling into public and private methods for better control
- Modified file operations to properly integrate with execution queue
- Updated document reset timing to prevent UI flickering

## Technical Details

The core improvement revolves around the introduction of a Promise-based execution queue:
```typescript
#globalExecutionQueue = Promise.resolve();

addToExecutionQueue(callback: () => Promise<void>) {
  this.#globalExecutionQueue = this.#globalExecutionQueue.then(() => callback());
}
```

This ensures that:
- File operations complete before related shell commands execute
- Commands execute in the exact order they were triggered
- UI updates happen at appropriate times without race conditions

## Benefits
1. Consistent command execution order during project reloads
2. Eliminated UI flickering during code streaming
3. More reliable file system synchronization
4. Better handling of rapid sequential operations

## Testing
- Verified correct operation order in new chat sessions
- Confirmed proper behavior in restored chat sessions
- Tested multiple rapid file operations and shell commands
- Verified proper handling of code streaming scenarios

## Migration Impact
- No breaking changes to existing functionality
- No API changes required for consumers
- Fully backward compatible with existing implementations

# Preview

https://github.com/user-attachments/assets/5a55f39a-1564-452a-81e7-f8d7761a37a1

### CODE REVIEW

**Comment by frogman544** [comment]
Great job! This is a huge win! Why is this not merged yet? What are we waiting for?

**Comment by chrismahoney** [comment]
I'm reviewing this right now, if it works like I think it does it is extremely important.

**Comment by chrismahoney** [comment]
👍 This is great. The glory is all yours, merge away. 👍

**Comment by thecodacus** [comment]
done !! 🥳

**Pull request merged**
