### PR TITLE
(Ready for review) - Small visual fix. Add background for chat window(currently transparent and looks ugly)

### PR DESCRIPTION
**Pull request by wonderwhy-er**
This PR includes two changes:
Enhance Chat Component Background:

Updated the BaseChat component to include a background and border styling. This resolves a visual issue where the area under the chat component appeared broken

Before:
Screenshot 2024-11-20 at 16 48 16

After:
Screenshot 2024-11-20 at 16 46 36

### CODE REVIEW

**Comment by kekePower** [comment]
Love it. I've noticed the same and, as you, thought it felt broken.

**Comment by wonderwhy-er** [comment]
I use git fetch remote pull/350/head:pr-350 to pull and test PRs locally fyi.

**Comment by kekePower** [comment]
LGTM. Tested and it looks great using the dark theme.

**Comment by EhabShahat** [comment]
Hi @wonderwhy-er 
Can we have a separate settings tab that have the model and api key, and also remove "using: [model name]" from chat.

**Pull request merged**
