### PR TITLE
feat: Setting Dialog

### PR DESCRIPTION
**Pull request by dustinwloring1988**
Below is a screenshot:

### CODE REVIEW

**Comment by dustinwloring1988** [comment]
With this you can deactivate providers from the providers dropdown,
API keys were moved to the setting

**Comment by thecodacus** [comment]
something is wrong,
I am getting this error 
image

**Comment by thecodacus** [comment]
looks good.. but i think we can have the option to edit the api keys in the and other interface same as before just the active and base url we can have in the settings modal.

**Comment by dustinwloring1988** [comment]
Nice and thanks for the work done to this.

**Pull request closed without merging**
