### PR TITLE
Added GitHub push functionality

### PR DESCRIPTION
**Pull request by goncaloalves**
Added Github push functionality: By pressing the button, the user will be asked for a name of a repo, his github username and his github token. 

This code is being run client side so the user will always be asked for his credentials (for security reasons).

I think the code is pretty straight forward. Let me know if you have any questions or would like any changes to the code.

### CODE REVIEW

**Comment by wonderwhy-er** [comment]
I was thinking about this. It pushes into the main branch, right?
Is it better to create new branches or pull requests? 

It is just on the main branch there could be conflicts
Any thoughts about that?

**Comment by goncaloalves** [comment]
It creates a repo and pushes it to the main branch. You can check an example in [here](https://github.com/goncaloalves/bolt-space-invaders2)

I don't really understand the rest of your questions. Can you please elaborate? I think I need a bit more detail to understand them.

**Comment by wonderwhy-er** [comment]
What I mean is that I have a concern about pushing directly to the main branch. In most cases, this is not a great practice, especially when the main branch is being worked on by others. The issue is that it can easily cause conflicts or overwrite someone else’s changes, which can disrupt the whole project.

A more effective approach is to create a new branch for your changes, and then submit a pull request. This allows for a smoother process where changes can be reviewed, conflicts can be resolved ahead of time, and everyone can stay on the same page without risking the stability of the main branch.

I am not interested in pushing into the main branch in that sense.
But that's me.

Maybe we can have an option of pushing to the main branch directly or making pull requests into the main branch.

**Comment by Felitendo** [comment]
Also please store the GitHub Token in an encrypted format so we don't have to login over and over again

**Comment by goncaloalves** [comment]
@wonderwhy-er Right now it is creating a new branch and pushing to main. 

I'm not really sure if what you are discussing is possible, because when using bolt, the code generated is "new" so there shouldn't exist a repo with that code already.

Can you give me a more detailed use case? I cannot wrap my mind around what you said.

@Felitendo Storing tokens in the frontend is generally considered a bad practice. There is feature request to store the AI APIs in the frontend but I think that should be reviewed. What is your take on it?

**Comment by Felitendo** [comment]
The best thing would be via making a docker-compose.yml file with full docker support. Then attaching bolt.new to a database like postgresql. Then making a register/login page that can be turned on/off via the Environtment Variable "ALLOW_SIGNUPS = true/false". Then creating a settings page with the options to add an AI API key and a GitHub API key. Then when creating a new Project, ask the user if he wants to sync a project to and from GitHub. If he says yes, then store the project files on postgresql and GitHub, if he says no, only store it on postgresql.

**Comment by coleam00** [comment]
This worked wonderfully, thank you @goncaloalves! Tested it out and here is the repo I pushed:

https://github.com/coleam00/bolt-generated-project

I appreciate the conversation here as well, thank you for your thoughts @Felitendo and @wonderwhy-er. I think there is some more work to be done to handle the token (and the API keys) better, I will create a follow up item for this.

Also making the UI better for the GitHub push would be a nice addition too! But for now this is great and I am merging it!

**Pull request merged**
