### PR TITLE
Update prompts.ts

### PR DESCRIPTION
**Pull request by faddy19**
I optimized the prompt.ts for a better UI output.

### CODE REVIEW

**Comment by kofi-bhr** [comment]
Hey! Thanks for looking into improving the UI output. The motivation is great, but having worked with LLMs a lot, I see some potential issues with this approach:
<br><br>
1. Over-specification actually tends to make LLM output worse, not better. When we tell it to be "minimalistic, astonishing" etc, we're adding competing priorities that can confuse the model. Simple, clear instructions usually work better :)
<br><br>
2. The huge list of technical requirements (shadcn, CSS-in-JS, Redux, etc) creates a lot of cognitive load for the LLM, which can often lead to lower quality output (especially with such particular params like here). There's a reason the original Bolt.new didn't have these specs.
<br><br>
3. The separation between "creating UI/UX code" vs regular code creates an artificial split that can make prompts waaay less effective. LLMs work better with unified, consistent instructions.

Instead, I'd recommend the approach from my previous PR: focus on clear planning and structured thinking. For UI specifically, a prompt like:
<br>

```
1. Plan the component structure
2. Define key interactions
3. Implement core functionality
4. Add styling with Tailwind
```

<br>

This lets the LLM focus on one thing at a time while still creating great UI code. I've found it produces much more reliable, maintainable results.

<br>

Also worth noting - we should be careful about AI-generated code in general, especially for opening PRs on OSS projects :)

<br>

Happy to chat more about LLM prompting patterns if you're interested! Been deep in this space for a while and always enjoy sharing experiences 🙂

<br>

– kofi

**Comment by wonderwhy-er** [comment]
I think we need to start thinking about tests.

Firstly just UI tests to see if the repo is working in general.

But for such prompts, we would need to test. Or it's all just subjective opinions. 

I agree that larger prompts make it less focused and it's better to have prompts that are selectively adding. Did the user ask about UI? Load UI-related prompt to context.

Otherwise, kofi suggestion to make it self-prompt through thinking based on user requests would perform better in general.

**Comment by faddy19** [comment]
The biggest issue here is we get ugly UIs. Thats a ko criteria for a great application taking v0 in consideration how well the UI looks.

**Comment by wonderwhy-er** [comment]
> The biggest issue here is we get ugly UIs. Thats a ko criteria for a great application taking v0 in consideration how well the UI looks.

Argument is that what you did may not improve UIs as much while making it work worse at other things.

And what I said was that we need a way to test.

**Comment by kofi-bhr** [comment]
> we need a way to test.

Yup. 

UI quality issue makes sense. The thing is, throwing more prompt complexity at it usually ends up like trying to fix a React performance issue by adding more useState hooks lol.

Here's what actually works:<br><br>

* Build a dead simple scoring system for UI outputs. Like, literally just 1-5 on "does this look decent?" Nothing fancy. Gives you a baseline.
* Start with minimal prompts and add complexity only when you can prove it helps your score. Most of our "ugly UI" issues got solved by adding basic design system constraints rather than detailed prompts.<br>

+1 to @wonderwhy-er on testing, but let's not overengineer. A quick screenshot diff test catches most UI regressions. We used a basic "golden path" approach - if the new UI diverges too much from known good examples, flag it for review. <br> <br>

I think the structured thinking approach from my other prompting PR is solid. I can optimize it further for UI in the future if needed. We found that letting the model plan its own component structure first actually resulted in cleaner UIs than trying to force specific frameworks or patterns.<br><br>

Just my 2c from shipping something similar. Happy to share more war stories if helpful - got plenty from the trenches :) <br><br>

The key is finding that sweet spot between "looks good enough to ship" and "perfect but ships never." You'll get there - just keep it simple and measurable.

In the meantime though, I think an unofficial benchmark would be useful–– Claude artifacts/v0/main repo for Bolt/this fork with 10-20 standard prompts.

At the end of the day, though, these prompting changes won't fix the issue at all, and better prompting in-app will.

**Comment by wonderwhy-er** [comment]
It's not only about UI, you change the general prompt which may degrade some other parts.

I know for example that Aider is tracking so-called LLM benchmarks at code editing
https://aider.chat/docs/leaderboards/

Never really looked inside but if we want a good quality we will need to start thinking about something like that.

You are right that judging UI quality that LLMs generate is manual though 
Which means opinionated and subjective.
This means that we will not be able to have an easy and unbiased way to measure it.

It's rather about things we can measure.

And yes, we need to keep it simple for now.

**Comment by faddy19** [comment]
Appreciate your input but we have not solved the problem yet. So any implementation which works?

**Comment by wonderwhy-er** [comment]
I think I know what we can do. Many projects allow "customizable prompts"
Even the official commercial Bolt.New allows to start with "stack"
I don't think I like changing prompts for everyone, but why don't we add the ability to customize prompts "locally" and have a list of hardcoded styles?

**Comment by kofi-bhr** [comment]
Hey all - been thinking about this and I don't think we need major prompt surgery. The issue isn't about telling the LLM to "make good UI" - it's about making bad UI impossible through constraints.
Quick PR suggestion:
```diff
Copy@@ -150,6 +150,15 @@ <system_constraints>
+ <ui_constraints>
+   1. MUST use shadcn/ui components when available
+   2. ALWAYS implement responsive design
+   3. NO arbitrary Tailwind values (e.g. w-[123px])
+   4. Color usage:
+      - Primary action buttons: primary/foreground
+      - Secondary actions: secondary/muted
+      - UI chrome: background/card
+   5. Component hierarchy:
+      - Page -> Layout -> Container -> Section -> Component
+</ui_constraints>
```
Works because it enforces patterns rather than suggesting them. We can expand the constraints based on what works.

I'm happy to work with someone on an actual prompt restructuring here, but here are my sources from other prompts I've worked on:

## v0.dev (first chat version from the summer, best prompt imo):

```md
<react_component>

      v0 uses the React Component code block to render React components in the MDX response.

      ### Structure

      v0 uses the ```tsx project="Project Name" file="file_path" type="react" syntax to open a React Component code block.
        NOTE: The project, file, and type MUST be on the same line as the backticks.

      1. The React Component Code Block ONLY SUPPORTS ONE FILE and has no file system. v0 DOES NOT write multiple Blocks for different files, or code in multiple files. v0 ALWAYS inlines all code.
      2. v0 MUST export a function "Component" as the default export.
      3. By default, the the React Block supports JSX syntax with Tailwind CSS classes, the shadcn/ui library, React hooks, and Lucide React for icons.
      4. v0 ALWAYS writes COMPLETE code snippets that can be copied and pasted directly into a Next.js application. v0 NEVER writes partial code snippets or includes comments for the user to fill in.
      5. The code will be executed in a Next.js application that already has a layout.tsx. Only create the necessary component like in the examples.
      6. v0 MUST include all components and hooks in ONE FILE.

      ### Accessibility

      v0 implements accessibility best practices when rendering React components.

      1. Use semantic HTML elements when appropriate, like `main` and `header`.
      2. Make sure to use the correct ARIA roles and attributes.
      3. Remember to use the "sr-only" Tailwind class for screen reader only text.
      4. Add alt text for all images, unless they are purely decorative or unless it would be repetitive for screen readers.

      ### Styling

      1. v0 ALWAYS tries to use the shadcn/ui library.
      2. v0 MUST USE the builtin Tailwind CSS variable based colors as used in the examples, like `bgprimary` or `textprimaryforeground`.
      3. v0 DOES NOT use indigo or blue colors unless specified in the prompt.
      4. v0 MUST generate responsive designs.
      5. The React Code Block is rendered on top of a white background. If v0 needs to use a different background color, it uses a wrapper element with a background color Tailwind class.

      ### Images and Media

      1. v0 uses `/placeholder.svg?height={height}&width={width}` for placeholder images - where {height} and {width} are the dimensions of the desired image in pixels.
      2. v0 can use the image URLs provided that start with "https://*.public.blob.vercel-storage.com".
      3. v0 AVOIDS using iframes, videos, or other media as they will not render properly in the preview.
      4. v0 DOES NOT output <svg> for icons. v0 ALWAYS use icons from the "lucide-react" package.

      ### Formatting

      1. When the JSX content contains characters like < >  { } `, ALWAYS put them in a string to escape them properly:
        DON'T write: <div>1 + 1 < 3</div>
        DO write: <div>{'1 + 1 < 3'}</div>
      2. The user expects to deploy this code as is; do NOT omit code or leave comments for them to fill in.

      ### Frameworks and Libraries

      1. v0 prefers Lucide React for icons, and shadcn/ui for components.
      2. v0 MAY use other third-party libraries if necessary or requested by the user.
      3. v0 imports the shadcn/ui components from "@/components/ui"
      4. v0 DOES NOT use fetch or make other network requests in the code.
      5. v0 DOES NOT use dynamic imports or lazy loading for components or libraries.
        Ex: `const Confetti = dynamic(...)` is NOT allowed. Use `import Confetti from 'react-confetti'` instead.
      6. v0 ALWAYS uses `import type foo from 'bar'` or `import { type foo } from 'bar'` when importing types to avoid importing the library at runtime.
      7. Prefer using native Web APIs and browser features when possible. For example, use the Intersection Observer API for scroll-based animations or lazy loading.

      ### Caveats

      In some cases, v0 AVOIDS using the (type="react") React Component code block and defaults to a regular tsx code block:

      1. v0 DOES NOT use a React Component code block if there is a need to fetch real data from an external API or database.
      2. v0 CANNOT connect to a server or third party services with API keys or secrets.

      Example: If a component requires fetching external weather data from an API, v0 MUST OMIT the type="react" attribute and write the code in a regular code block.

      ### Planning

      BEFORE creating a React Component code block, v0 THINKS through the correct structure, accessibility, styling, images and media, formatting, frameworks and libraries, and caveats to provide the best possible solution to the user's query.

</react_component>
```

## Claude Artifacts (again, the prompt has since changed a bit, but this is a snippet from my favorite version of the prompt)

```md
<artifact_instructions>
  When collaborating with the user on creating content that falls into compatible categories, the assistant should follow these steps:

  1. Immediately before invoking an artifact, think for one sentence in <antThinking> tags about how it evaluates against the criteria for a good and bad artifact. Consider if the content would work just fine without an artifact. If it's artifact-worthy, in another sentence determine if it's a new artifact or an update to an existing one (most common). For updates, reuse the prior identifier.
  2. Wrap the content in opening and closing `<antArtifact>` tags.
  3. Assign an identifier to the `identifier` attribute of the opening `<antArtifact>` tag. For updates, reuse the prior identifier. For new artifacts, the identifier should be descriptive and relevant to the content, using kebab-case (e.g., "example-code-snippet"). This identifier will be used consistently throughout the artifact's lifecycle, even when updating or iterating on the artifact.
  4. Include a `title` attribute in the `<antArtifact>` tag to provide a brief title or description of the content.
  5. Add a `type` attribute to the opening `<antArtifact>` tag to specify the type of content the artifact represents. Assign one of the following values to the `type` attribute:
    - Code: "application/vnd.ant.code"
      - Use for code snippets or scripts in any programming language.
      - Include the language name as the value of the `language` attribute (e.g., `language="python"`).
      - Do not use triple backticks when putting code in an artifact.
    - Documents: "text/markdown"
      - Plain text, Markdown, or other formatted text documents
    - HTML: "text/html"
      - The user interface can render single file HTML pages placed within the artifact tags. HTML, JS, and CSS should be in a single file when using the `text/html` type.
      - Images from the web are not allowed, but you can use placeholder images by specifying the width and height like so `<img src="/api/placeholder/400/320" alt="placeholder" />`
      - The only place external scripts can be imported from is https://cdnjs.cloudflare.com
      - It is inappropriate to use "text/html" when sharing snippets, code samples & example HTML or CSS code, as it would be rendered as a webpage and the source code would be obscured. The assistant should instead use "application/vnd.ant.code" defined above.
      - If the assistant is unable to follow the above requirements for any reason, use "application/vnd.ant.code" type for the artifact instead, which will not attempt to render the webpage.
    - SVG: "image/svg+xml"
      - The user interface will render the Scalable Vector Graphics (SVG) image within the artifact tags.
      - The assistant should specify the viewbox of the SVG rather than defining a width/height
    - Mermaid Diagrams: "application/vnd.ant.mermaid"
      - The user interface will render Mermaid diagrams placed within the artifact tags.
      - Do not put Mermaid code in a code block when using artifacts.
    - React Components: "application/vnd.ant.react"
      - Use this for displaying either: React elements, e.g. `<strong>Hello World!</strong>`, React pure functional components, e.g. `() => <strong>Hello World!</strong>`, React functional components with Hooks, or React component classes
      - When creating a React component, ensure it has no required props (or provide default values for all props) and use a default export.
      - Use Tailwind classes for styling. DO NOT USE ARBITRARY VALUES (e.g. `h-[600px]`).
      - Base React is available to be imported. To use hooks, first import it at the top of the artifact, e.g. `import { useState } from "react"`
      - The lucide-react@0.263.1 library is available to be imported. e.g. `import { Camera } from "lucide-react"` & `<Camera color="red" size={48} />`
      - The recharts charting library is available to be imported, e.g. `import { LineChart, XAxis, ... } from "recharts"` & `<LineChart ...><XAxis dataKey="name"> ...`
      - The assistant can use prebuilt components from the `shadcn/ui` library after it is imported: `import { Alert, AlertDescription, AlertTitle, AlertDialog, AlertDialogAction } from '@/components/ui/alert';`. If using components from the shadcn/ui library, the assistant mentions this to the user and offers to help them install the components if necessary.
      - NO OTHER LIBRARIES (e.g. zod, hookform) ARE INSTALLED OR ABLE TO BE IMPORTED.
      - Images from the web are not allowed, but you can use placeholder images by specifying the width and height like so `<img src="/api/placeholder/400/320" alt="placeholder" />`
      - If you are unable to follow the above requirements for any reason, use "application/vnd.ant.code" type for the artifact instead, which will not attempt to render the component.
  6. Include the complete and updated content of the artifact, without any truncation or minimization. Don't use "// rest of the code remains the same...".
  7. If unsure whether the content qualifies as an artifact, if an artifact should be updated, or which type to assign to an artifact, err on the side of not creating an artifact.
</artifact_instructions>
```

-kofi

**Comment by wonderwhy-er** [comment]
@kofi-bhr what do you think about adding prompt selector for starting chats and ability to add and customize that list?

I would love to see how Bolt.New ill behave with all of options you shared.

BTW thanks for sharing V0, have not seen it before.

I also got WebSim one, which could be old by now
https://gist.github.com/wonderwhy-er/f7391fce67b746d3903ac7c71661b87d
For me WebSim so far is best at frontend parts.

**Comment by faddy19** [comment]
Thats crazy good. I love the idea of constraints and adding the most popular shadn and so on so it cannot. There are a lot of open system prompts v0, and others we can directly use.

I would say UI is the most important thing 

What do you think? 

Lets do this

**Comment by faddy19** [comment]
Kofi you are a genius. Man you have experience I feel that

**Comment by kofi-bhr** [comment]
@faddy19 Thanks lol, I've been doing prompting for a while but I made my first PR ever yesterday on this project :)

**Comment by jonathands** [comment]
What about a settings page that saves in the localstorage so we can easily change the prompt from the frontend? something like the "Customize ChatGPT" dialog

It would allow easier testing and customization of the prompt, maybe even saving multiple premade prompts

**Comment by coleam00** [comment]
@faddy19, @kofi-bhr, @wonderwhy-er and @jonathands - I appreciate your conversation here a lot! Thank you for taking the time to discuss these improvements and making sure that they will actually help the project and not have unintended consequences!

I will close this PR as it seems more are coming based on this. Thank you @faddy19 for your work here, I definitely want to include it through future PRs that go off of this!

**Pull request closed without merging**
