### PR TITLE
fix: respect provider choice from UI

### PR DESCRIPTION
**Pull request by TommyHolmberg**
This change ensures the `streamText` function respects the provider choice made in the UI.

I am unable to test this thoroughly because I don't have API keys for the providers, as I use local models.

Even locally, this still doesn't work, but it's a step in the right direction. The URL calls are correct, but they aren't reaching the local LiteLLM server for some reason.

### CODE REVIEW

**Comment by nandan121** [comment]
> This change ensures the `streamText` function respects the provider choice made in the UI.
> 
> I am unable to test this thoroughly because I don't have API keys for the providers, as I use local models.
> 
> Even locally, this still doesn't work, but it's a step in the right direction. The URL calls are correct, but they aren't reaching the local LiteLLM server for some reason.
Hello Tommy,
I could get it working for liteLLM. I used your https://github.com/TommyHolmberg/bolt.new-any-llm/tree/respect-provider-choice , my constants file was https://github.com/nandan121/bolt.new-any-llm/blob/417307bdb5edf2b4a5da92c9d1c6ec15b8f68923/app/utils/constants.ts

I tried one step at a time with the free API from Mistral to try. https://docs.litellm.ai/docs/providers/mistral

**Comment by nandan121** [comment]
image
It seems that the message has "Provider" in it, and it needs to be removed

**Comment by TommyHolmberg** [comment]
> image It seems that the message has "Provider" in it, and it needs to be removed

I completely overlooked that. I found the sanitize method for it and could fix it rather easily. Try the PR now.

**Comment by nandan121** [comment]
> > It seems that the message has "Provider" in it, and it needs to be removed
> 
> I completely overlooked that. I found the sanitize method for it and could fix it rather easily. Try the PR now.

Tried, and it works as expecms that the message has "Provider" in it, and it needs to be removed
> 
> I completely overlooked that. I found the sanitize method for it and could fix it rather easily. Try the PR now.

Tried, and it works as expected(no model name or provider name).
BUT, my suggestion would be to have it in the chat... It is nice and does not take space.
ted.
BUT, my suggestion would be to have it in the chat... It is nice and does not take space.

I would suggest that in https://github.com/coleam00/bolt.new-any-llm/pull/188/files#diff-dd246a18ac09a3e1a293988bf2f81b4f246f4c4aa03db23db48f79371c378981 I would probably have it in my version.

  return content.replace(modificationsRegex, '').replace(MODEL_REGEX, '$1').replace(PROVIDER_REGEX, ' ($1)\n\n').trim();

could be better. I will allow the @coleam00  to make that decision.

image

**Comment by TommyHolmberg** [comment]
> > > It seems that the message has "Provider" in it, and it needs to be removed
> > 
> > 
> > I completely overlooked that. I found the sanitize method for it and could fix it rather easily. Try the PR now.
> 
> Tried, and it works as expecms that the message has "Provider" in it, and it needs to be removed
> 
> > I completely overlooked that. I found the sanitize method for it and could fix it rather easily. Try the PR now.
> 
> Tried, and it works as expected(no model name or provider name).
> 
> BUT, my suggestion would be to have it in the chat... It is nice and does not take space.
> 
> I would suggest that in https://github.com/coleam00/bolt.new-any-llm/pull/188/files#diff-dd246a18ac09a3e1a293988bf2f81b4f246f4c4aa03db23db48f79371c378981 I would probably have it in my version.
> 
> ` return content.replace(modificationsRegex, '').replace(MODEL_REGEX, '$1').replace(PROVIDER_REGEX, ' ($1)\n\n').trim();`
> 
> could be better. I will allow the @coleam00 to make that decision.
> 

I think it looks great! And good catch with those line breaks. I was wondering why the message boxes looked off.

**Comment by coleam00** [comment]
I appreciate the back and forth here @TommyHolmberg and @nandan121! Could you clarify if this is ready to merge now?

**Comment by TommyHolmberg** [comment]
I added `Using:` before the model and provider to clarify what it's about. The best would be if we could get the model and provider into the response message, but that requires a bit of work and it doesnt belong in this PR.

@coleam00 In my opinion it is ready to merge.

**Comment by nandan121** [comment]
> I appreciate the back and forth here @TommyHolmberg and @nandan121! Could you clarify if this is ready to merge now?

Thanks @coleam00  and @TommyHolmberg . I tested it once, it looks great. All is working and ready to merge.
image

**Pull request merged**
