### PR TITLE
feat(chat): add image upload functionality to chat component

### PR DESCRIPTION
**Pull request by vgcman16**
This pull request introduces the ability for users to upload images within the chat interface. The following changes have been made:

Image Upload Component: A new ImageUpload component has been created to allow users to select and upload images.
Chat Client Modifications: The Chat.client.tsx file has been updated to manage the state of the uploaded image and to include the image in the chat messages.
Base Chat Integration: The BaseChat.tsx file has been modified to integrate the ImageUpload component and display the name of the attached image when selected.
User Experience: Users can now attach images to their messages, enhancing the chat functionality and allowing for richer interactions.
This feature aims to improve user engagement and provide a more dynamic chat experience.

### CODE REVIEW

**Comment by wonderwhy-er** [comment]
Ouh boy man, you made a lot of stuff that seems to have nothing to do with image upload...
Can you separate?

**Comment by vgcman16** [comment]
> Ouh boy man, you made a lot of stuff that seems to have nothing to do with image upload... Can you separate?

how do I do that

**Comment by omer72** [comment]
I tired it :
I'm sorry, but I can't decode or interpret that image. It appears to be a base64 encoded string representing an image, but I don't have the capability to decode it or understand its contents. If you'd like me to help with something specific related to this image, please provide more context or ask a question about what you're trying to do with it.

**Comment by wonderwhy-er** [comment]
@vgcman16 
I mean, your pull request shows 26 thousand lines of changes, that is too much...
You just pushed in more... Using a Monaco code editor instead of CodeMirror...

I am against merging that for many reasons. Too many changes in one PR.
Some of these may conflict with future mergers with the original bolt repo from StackBlitz.

You need to learn how to work with multiple branches of Git Hub first.
Then try to take a clean version of Coleman repo and cherry-pick into it a minimal amount of changes for using images, throwing out everything that is not related.

You have here something 26 PRs in one, no one gonna read and merge that...

**Comment by vgcman16** [comment]
> Screenshot 2024-10-25 at 11 02 29
> I tired it : I'm sorry, but I can't decode or interpret that image. It appears to be a base64 encoded string representing an image, but I don't have the capability to decode it or understand its contents. If you'd like me to help with something specific related to this image, please provide more context or ask a question about what you're trying to do with it.

I’ll see if I can fix it after work

**Comment by vgcman16** [comment]
> @vgcman16 I mean, your pull request shows 26 thousand lines of changes, that is too much... You just pushed in more... Using a Monaco code editor instead of CodeMirror...
> 
> I am against merging that for many reasons. Too many changes in one PR. Some of these may conflict with future mergers with the original bolt repo from StackBlitz.
> 
> You need to learn how to work with multiple branches of Git Hub first. Then try to take a clean version of Coleman repo and cherry-pick into it a minimal amount of changes for using images, throwing out everything that is not related.
> 
> You have here something 26 PRs in one, no one gonna read and merge that...

I apologize I was trying make it better

**Comment by wonderwhy-er** [comment]
> > @vgcman16 I mean, your pull request shows 26 thousand lines of changes, that is too much... You just pushed in more... Using a Monaco code editor instead of CodeMirror...
> > I am against merging that for many reasons. Too many changes in one PR. Some of these may conflict with future mergers with the original bolt repo from StackBlitz.
> > You need to learn how to work with multiple branches of Git Hub first. Then try to take a clean version of Coleman repo and cherry-pick into it a minimal amount of changes for using images, throwing out everything that is not related.
> > You have here something 26 PRs in one, no one gonna read and merge that...
> 
> I apologize I was trying make it better

No no, good work, no need to apologize, it just needs to be separated into individual things that can be judged, fixed, merged in separation.

**Comment by vgcman16** [comment]
> > > @vgcman16 I mean, your pull request shows 26 thousand lines of changes, that is too much... You just pushed in more... Using a Monaco code editor instead of CodeMirror...
> > > I am against merging that for many reasons. Too many changes in one PR. Some of these may conflict with future mergers with the original bolt repo from StackBlitz.
> > > You need to learn how to work with multiple branches of Git Hub first. Then try to take a clean version of Coleman repo and cherry-pick into it a minimal amount of changes for using images, throwing out everything that is not related.
> > > You have here something 26 PRs in one, no one gonna read and merge that...
> > 
> > 
> > I apologize I was trying make it better
> 
> No no, good work, no need to apologize, it just needs to be separated into individual things that can be judged, fixed, merged in separation.

Okay when I get home I’ll try to use my terminal to separate the PR individually

**Pull request closed without merging**
