### PR TITLE
Ollama not respecting model selection

### PR DESCRIPTION
**Pull request by dustinwloring1988**
Fixes bug with Ollama not respecting model selection

### CODE REVIEW

**Comment by coleam00** [comment]
Thank you @dustinwloring1988!

**Comment by miyaniakshar1234** [comment]
Screenshot (13)
i see that error each time i request i have tried pnpm and docker both but it not resolved

**Comment by dustinwloring1988** [comment]
@miyaniakshar1234 how is ollama setup, in docker? also did you set the baseURL for Ollama in the settings or the .env.local

**Comment by kalyanipujari204** [comment]
can you tell me where i can get that ollama base url

**Comment by devictang** [comment]
> can you tell me where i can get that ollama base url

I think that should be http://localhost:11434/ by default

But I have the same issue that bolt.diy is asking me for ollama api keys despite I have set the ollama url.

I installed bolt from pinokio.

**Pull request merged**
