### PR TITLE
feat: added sync files to selected local folder function is created.Yarn package manager fixes, styling fixes. Sass module fix. Added Claude model for open router.

### PR DESCRIPTION
**Pull request by muzafferkadir**
## Changes

1. Added new functionality to sync files to a selected local folder
2. Implemented Yarn package manager fixes
3. Applied styling fixes
4. Resolved Sass module configuration issue
5. Added Claude model support for OpenRouter

### Sync Files Feature

- Created a new `handleSyncFiles` function in the Workbench component
- Added a "Sync Files" button to the Workbench UI
- Implemented `syncFiles` method in the WorkbenchStore class to handle file synchronization
- Added error handling and success/failure toasts for the sync process

### Package Manager and Styling

- Updated package.json to use yarn without any error
- Applied various styling fixes (details to be added)

### Sass Module Fix

- Updated Vite configuration to use the modern compiler API for Sass

### Claude Model Support

- Added Claude 3.5 Sonnet and Claude 3 Haiku models for OpenRouter

## Code Changes

- Modified `Workbench.tsx` to include the new sync files functionality
- Updated `WorkbenchStore.ts` with the `syncFiles` method
- Added new model options in the AI models configuration
- Updated `vite.config.ts` to include Sass preprocessor options

## Testing

Please test the following:

1. Sync Files functionality
2. Styling changes across the application
3. Sass compilation
4. New Claude models with OpenRouter

### CODE REVIEW

**Comment by wonderwhy-er** [comment]
Oh, I was thinking about this approach too, but it will work only in Chrome, right? 
https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker#browser_compatibility

I guess its fine, graceful degradation, just must not be "required" feature.

**Comment by wonderwhy-er** [comment]
I will be working on my fork tomorrow and want to merge something like this into it. Will check how this works tomorrow and merge, will reference you if your version will work well.

**Comment by muzafferkadir** [comment]
> Oh, I was thinking about this approach too, but it will work only in Chrome, right? https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker#browser_compatibility
> 
> I guess its fine, graceful degradation, just must not be "required" feature.

Unfortunately, it works only for Chrome at the moment. Maybe it can be refactored using File API. I'll take a look

**Comment by wonderwhy-er** [comment]
> > Oh, I was thinking about this approach too, but it will work only in Chrome, right? https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker#browser_compatibility
> > I guess its fine, graceful degradation, just must not be "required" feature.
> 
> Unfortunately, it works only for Chrome at the moment. Maybe it can be refactored using File API. I'll take a look

I just tied your version
Works fine, I would like to to sync on each chance and add ability to save versions


I will make my "fork" of it and reference to here

**Comment by wonderwhy-er** [comment]
Ok, I made bunch of changes
Added to my fork
Added you to readme as initial contributor

https://github.com/wonderwhy-er/bolt.free-download-zip-live-folder-sync

**Comment by coleam00** [comment]
This is fantastic, thank you @muzafferkadir! I would suggest having a way to tell users that this is a one way sync and that it only works on Chrome for now. But I will still merge this because I love this addition!

**Comment by chimph** [comment]
> This is fantastic, thank you @muzafferkadir! I would suggest having a way to tell users that this is a one way sync and that it only works on Chrome for now. But I will still merge this because I love this addition!

Tried on Firefox and Brave before arriving here to see what was the issue. Blew the dust off Chrome to see that it does indeed work

**Comment by ro-stack-ai** [comment]
Sync Files not working for me on chrome..

**Pull request merged**
