### PR TITLE
Add provider filtering on model list

### PR DESCRIPTION
**Pull request by jasonm23**
We can do a lot more on model selection, just using ollama to give us a list of available local models will be a nice next step.

In the meantime here's a selector to filter down the static model list by providers

Enjoy.

### CODE REVIEW

**Comment by jasonm23** [comment]
Note I split out the model selector into it's own component but I've left it in the base chat for this step.

**Comment by coleam00** [comment]
@jasonm23 This is so helpful - thank you so much for adding a provider filter!

**Comment by jasonm23** [comment]
Happy to help

**Comment by jasonm23** [comment]
@coleam00 please add me as a contributor so I can help you keep the code up to date from Stackblitz.

**Comment by coleam00** [comment]
@jasonm23 I have added you - thank you!!

**Pull request merged**
