### PR TITLE
fix: dockerstart fix in package.json for production build (Ready for review)

### PR DESCRIPTION
**Pull request by dustinwloring1988**
Docker Production Build Fix.

Just make your .env.local file and run 'pnpm run dockerbuild:prod && docker-compose --profile production up' if this dose not work use 'pnpm run dockerbuild:prod && docker compose --profile production up'

Fixes this issue: https://github.com/coleam00/bolt.new-any-llm/issues/369 & https://github.com/coleam00/bolt.new-any-llm/issues/353

Windows: Working

Linux: working

### CODE REVIEW

**Comment by coleam00** [comment]
Thank you @dustinwloring1988!

Did you test with Linux or could someone test this with Linux? I remember some of those "binding" changes were made initially to help with getting this to work on Linux. Might be misremembering though.

**Comment by dustinwloring1988** [comment]
@coleam00 No I did not but am spinning up a vm for testing, ill post the results

**Comment by chrismahoney** [comment]
I'll test this as well via Linux, I had a small fix branch in the works to blow up bindings.sh run with a clear error if the .env.local file is missing to avoid situations where the directions weren't followed. Will add that here as a suggested change after tests. 🙌

**Comment by dustinwloring1988** [comment]
It did not work in Ubuntu for me

**Comment by chrismahoney** [comment]
If you have some results output, might be able to help there before I spin one up myself a bit later.

**Comment by chrismahoney** [comment]
> I'll test this as well via Linux, I had a small fix branch in the works to blow up bindings.sh run with a clear error if the .env.local file is missing to avoid situations where the directions weren't followed. Will add that here as a suggested change after tests. 🙌

Note: Keeping this here for later, the failure exit if .env.local is missing.

```
diff --git a/bindings.sh b/bindings.sh
old mode 100755
new mode 100644
index c8a86ea..63e7974
--- a/bindings.sh
+++ b/bindings.sh
@@ -2,6 +2,12 @@
 
 bindings=""
 
+# Check if .env.local exists
+if [ ! -f .env.local ]; then
+  echo "Error: .env.local file not found."
+  exit 1
+fi
+
 while IFS= read -r line || [ -n "$line" ]; do
   if [[ ! "$line" =~ ^# ]] && [[ -n "$line" ]]; then
     name=$(echo "$line" | cut -d '=' -f 1)

```

**Comment by dustinwloring1988** [comment]
@chrismahoney will post out put here soon, even with .env.local

**Comment by dustinwloring1988** [comment]
Correction it was user error on my part 'docker-compose' was not recognized so I apt installed it when I should have used 'docker compose'. All working

**Pull request closed without merging**
