### PR TITLE
feat: lm studio integration

### PR DESCRIPTION
**Pull request by karrot0**
LM Studio Integration, this is a simple integration, there are still errors with the repo that limit the ability for open source models to use the shell commands and webcontainer.

Right now this is basically just a chat bot.
Currently the bolt.new system prompt is so long that the context window shortens even for smaller models and might not send messages.

image
image

### CODE REVIEW

**Comment by wonderwhy-er** [comment]
Not ready for merge, I get errors locally after merging with master about openai api keys that are not really needed for LMStudio 

Model list loading works though

**Comment by wonderwhy-er** [comment]
Investigated more, I got two errors before I got it working.
1. OpenAI with LM Studio url that is used for this seeks API key for OpenAI, if its not set it throws an error
So what I did to make it work was this:
  const lmstudio = createOpenAI({
    baseUrl: `${baseURL}/v1`,
    apiKey: "",
  });
  Then it worked for me

2. Second issue I got was that by default Codestral that I tried it with had 4k context window and initial prompt is a little bit over 4k, so it was failing with returning ""
But that is not problem with your PR


Can you fix 1? Then we can merge

**Comment by karrot0** [comment]
> Investigated more, I got two errors before I got it working.
> 
> 1. OpenAI with LM Studio url that is used for this seeks API key for OpenAI, if its not set it throws an error
>    So what I did to make it work was this:
>    const lmstudio = createOpenAI({
>    baseUrl: `${baseURL}/v1`,
>    apiKey: "",
>    });
>    Then it worked for me
> 2. Second issue I got was that by default Codestral that I tried it with had 4k context window and initial prompt is a little bit over 4k, so it was failing with returning ""
>    But that is not problem with your PR
> 
> Can you fix 1? Then we can merge

Just looked at your comment, added it.

**Comment by wonderwhy-er** [comment]
Works, merging
image

**Comment by godscodes** [comment]
It's working fine on 127.0.0.1:1234 instead of localhost:1234

**Pull request merged**
